apiVersion: v1
kind: ResourceQuota
metadata:
  name: sample-resourcequota-usable
  namespace: default
spec:
  hard:
    requests.cpu: 2
    requests.memory: 2Gi
    requests.storage: 5Gi 
    sample-storageclass.storageclass.storage.k8s.io/requests.storage: 5Gi
    requests.ephemeral-storage: 5Gi

    limits.cpu: 4
    limits.memory: 4Gi
    limits.ephemeral-storage: 10Gi
