apiVersion: v1
kind: ResourceQuota
metadata:
  name: sample-resourcequota-count-old
  namespace: default
spec:
  hard:
    services.loadbalancers: 10
    services.nodeports: 10
    pods: 10
    persistentvolumeclaims: 10
    replicationcontrollers: 10
    secrets: 10
    configmaps: 10
    services: 10
    resourcequotas: 10

